# Generated by Django 5.2.6 on 2025-09-20 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
