# Generated by Django 5.2.6 on 2025-09-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
